[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  /fluent-bit/etc/parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name             tail
    Path             /var/log/ballerina/*.log, /var/log/ballerina/**/*.log
    Parser           bal_logfmt_parser
    Tag              ballerina.*
    Refresh_Interval 5
    Mem_Buf_Limit    256MB
    Skip_Long_Lines  On
    Read_from_Head   On
    Path_Key         log_file_path

[FILTER]
    Name    lua
    Match   ballerina.*
    Script  /fluent-bit/scripts/scripts.lua
    Call    extract_app_from_path

[FILTER]
    Name  record_modifier
    Match ballerina.*
    Record product   integration
    Record component ballerina

[OUTPUT]
    Name       newrelic
    Match      ballerina.*
    licenseKey ${NEW_RELIC_LICENSE_KEY}
    endpoint   https://log-api.newrelic.com/log/v1
    compress   gzip
    